# Generated by Django 5.2 on 2025-05-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recruit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sheet_name", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
