# Generated by Django 5.2 on 2025-05-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruit", "0002_recruit_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recruit",
            old_name="email",
            new_name="mail",
        ),
    ]
