# Generated by Django 5.2 on 2025-05-27 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruit", "0003_rename_email_recruit_mail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recruit",
            old_name="sheet_name",
            new_name="documents_status",
        ),
        migrations.RemoveField(
            model_name="recruit",
            name="mail",
        ),
        migrations.AddField(
            model_name="recruit",
            name="entry_day",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
